# Generated by Django 3.0.3 on 2020-03-02 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=200, verbose_name='Company name')),
                ('contractor_nip', models.CharField(blank=True, max_length=12, verbose_name='NIP')),
                ('contractor_regon', models.IntegerField(blank=True, null=True, verbose_name='REGON')),
                ('contractor_phone', models.CharField(blank=True, max_length=20, verbose_name='Phone number')),
                ('contractor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='invoice issue date')),
                ('invoice_number', models.CharField(max_length=80, unique=True, verbose_name='invoice number')),
                ('sell_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of sell')),
                ('payment_form', models.CharField(max_length=80, verbose_name='payment form')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of sell')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Contractor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Product/service namme')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='City or Town')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Street')),
                ('number', models.CharField(max_length=100, verbose_name='House number')),
                ('post', models.CharField(max_length=200, verbose_name='Post office')),
                ('postal_code', models.CharField(max_length=200, verbose_name='Postal code')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='Notes')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Contractor')),
            ],
        ),
    ]
