# Generated by Django 3.0.3 on 2020-03-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='city',
            field=models.CharField(default='nowy sacz', max_length=200, verbose_name='City or Town'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='notes',
            field=models.CharField(blank=True, max_length=250, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='number',
            field=models.CharField(default='1', max_length=100, verbose_name='House number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='post',
            field=models.CharField(default='krakow', max_length=200, verbose_name='Post office'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='postal_code',
            field=models.CharField(default='33-300', max_length=200, verbose_name='Postal code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Street'),
        ),
        migrations.DeleteModel(
            name='ContractorAddress',
        ),
    ]
