# Generated by Django 3.0.3 on 2020-03-26 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=datetime.date.today, verbose_name='invoice issue date'),
        ),
    ]
