# Generated by Django 3.0.3 on 2020-03-26 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20200326_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='invoice issue date'),
        ),
    ]
