# Generated by Django 3.0.1 on 2020-01-22 22:02

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='contractor_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Company name'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_nip',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='NIP'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contractor_regon',
            field=models.IntegerField(blank=True, null=True, verbose_name='REGON'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['pk'], unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=80, verbose_name='invoice number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_form',
            field=models.CharField(max_length=80, verbose_name='payment form'),
        ),
    ]
