# Generated by Django 3.0.1 on 2020-01-23 22:11

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20200122_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='City or Town')),
                ('street', models.CharField(blank=True, max_length=200, null=True, verbose_name='Street')),
                ('number', models.CharField(max_length=100, verbose_name='House number')),
                ('post', models.CharField(max_length=200, verbose_name='Post office')),
                ('postal_code', models.CharField(max_length=200, verbose_name='Postal code')),
                ('notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Notes')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['pk'], unique=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Contractor')),
            ],
        ),
    ]
