# Generated by Django 3.0.1 on 2020-01-24 19:23

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_contractoraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractoraddress',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Contractor'),
        ),
        migrations.AlterField(
            model_name='contractoraddress',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from=['pk'], unique=True),
        ),
    ]
