# Generated by Django 3.0.1 on 2020-02-08 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20200128_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='contractoraddress',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='invoiceposition',
            name='user',
        ),
        migrations.AddField(
            model_name='invoice',
            name='contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoices.Contractor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceposition',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractoraddress',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Contractor'),
        ),
    ]
