# Generated by Django 3.0.1 on 2020-02-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20200208_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractoraddress',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Contractor'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Contractor'),
        ),
        migrations.AlterField(
            model_name='invoiceposition',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
    ]
