# Generated by Django 3.0.1 on 2020-01-21 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='invoice issue date')),
                ('invoice_number', models.CharField(max_length=80)),
                ('sell_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of sell')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['pk'], unique=True)),
                ('payment_form', models.CharField(max_length=80)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of sell')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
