# Generated by Django 3.0.1 on 2020-01-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='invoice',
        ),
    ]
