export const GET_INVOICES = "GET_INVOICES";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const ADD_INVOICE = "ADD_INVOICE";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
